project_id = "rzbtrvceflkvrhphbksx"

[auth]
enabled = true
# The base URL of your website
site_url = "https://rzbtrvceflkvrhphbksx.supabase.co"

[edge-runtime]
policy = "per_worker"

[functions.create-project]
verify_jwt = true

[functions.get-projects]
verify_jwt = true

[functions.ai-generate]
verify_jwt = true

[functions.get-usage]
verify_jwt = true

[functions.llm]
verify_jwt = true

[functions.chat]
verify_jwt = true

[functions.generate]
verify_jwt = false

[functions.validate-code] 
verify_jwt = false

[functions.update-project]
verify_jwt = true
