// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzbtrvceflkvrhphbksx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6YnRydmNlZmxrdnJocGhia3N4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MjkyNDUsImV4cCI6MjA3MjQwNTI0NX0.8ajeq8EPBtr27fRs4NONXP2Bp8m5YDKm3AenlKRJY6o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});